apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-api-dev
nameSuffix: -dev
labels:
  - pairs:
      environment: dev
    includeSelectors: true
resources:
  - ../../base
  - runtime-config.yaml
patches:
  - path: deployment-patch.yaml
