apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/sample-platform.yaml
  - applications/sample-api-dev.yaml
  - applications/sample-api-test.yaml
  - applications/sample-api-prod.yaml

