apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications/sample-api-helm-dev.yaml
  - applications/sample-api-helm-test.yaml
  - applications/sample-api-helm-prod.yaml

